name: Sync with School Repository

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Configure SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Add School Repository Remote
        run: git remote add school-repo git@github.com:easv-devops/CurrencyConverter_CL.git

      - name: Fetch School Repository
        run: git fetch school-repo

      - name: Merge Changes
        run: git merge school-repo/master --no-commit --no-ff --allow-unrelated-histories

      - name: Commit Changes
        run: git commit -m "Sync changes from school repository"

      - name: Push Changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # GitHub Personal Access Token
        run: |
          git push origin master
