name: Sync with School Repository

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Add School Repository Remote
        run: git remote add school-repo git@github.com:easv-devops/CurrencyConverter_CL.git

      - name: Fetch School Repository
        run: git fetch school-repo

      - name: Merge Changes
        run: git merge school-repo/master --no-commit --no-ff

      - name: Commit Changes
        run: git commit -m "Sync changes from school repository"

      - name: Push Changes
        run: git push origin master
